-- SQL import file generated by CFEngine using mustache template
-- generate connection entry within guacamole_db using CFE vars from manage/guacamole/database.cf

{{#classes.parent_group_not_defined}}
-- START GLOBAL PARAMETERS FOR CONNECTION GROUP IF IT HAS A PARENT GROUP
INSERT INTO guacamole_connection_group (connection_group_name, type, max_connections, max_connections_per_user, enable_session_affinity)
VALUES ('{{{vars.guac_create_connection_group.groupname}}}',
        '{{{vars.guac_create_connection_group.type}}}', -- must be ORGANIZATIONAL or BALANCING
        '{{{vars.guac_database_vars.max_connections_per_group}}}',
        '{{{vars.guac_database_vars.max_connections_per_user_per_group}}}',
        '{{{vars.guac_create_connection_group.enable_session_affinity}}}' -- must be TRUE or FALSE
       );
-- END GLOBAL PARAMETERS
{{/classes.parent_group_not_defined}}

{{#classes.parent_group_defined}}
-- START GLOBAL PARAMETERS FOR CONNECTION GROUP IF IT HAS A PARENT GROUP
INSERT INTO guacamole_connection_group (connection_group_name, type, parent_id, max_connections, max_connections_per_user, enable_session_affinity)
VALUES ('{{{vars.guac_create_connection_group.groupname}}}',
        '{{{vars.guac_create_connection_group.type}}}', -- must be ORGANIZATIONAL or BALANCING
        '{{{vars.guac_create_connection_group.mysql_parent_id_result}}}', -- id gained from mysql query on parent_group
	'{{{vars.guac_database_vars.max_connections_per_group}}}',
        '{{{vars.guac_database_vars.max_connections_per_user_per_group}}}',
        '{{{vars.guac_create_connection_group.enable_session_affinity}}}' -- must be TRUE or FALSE
       );
-- END GLOBAL PARAMETERS
{{/classes.parent_group_defined}}
