-- SQL import file generated by CFEngine using mustache template
-- generate connection entry within guacamole_db using CFE vars from manage/guacamole/database.cf

INSERT INTO guacamole_user (username, full_name, email_address, organization, organizational_role)
VALUES ('{{{vars.guac_create_user.username}}}',
        '{{{vars.guac_create_user.full_name}}}',
        '{{{vars.guac_create_user.email_address}}}',
        '{{{vars.guac_create_user.organization}}}',
        '{{{vars.guac_create_user.role}}}'
       );
